version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/php:7.4.9-fpm
    environment:
      APP_ENV: testing
jobs:
  build:
    executor:
      name: my-executor
    environment:
      APP_NAME: test
    steps:
      - run: echo Hello World
